version: '3'

services:
  db:
    tty: true
    image: postgres
    ports:
      - 5432:5432
    hostname: postgres
  web:
    tty: true
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
